version: '3.8'

# Development specific overrides
networks:
  loadsure-network:
    name: loadsure-network-dev

services:
  # Development-specific environment variables for PostgreSQL
  postgres:
    environment:
      - POSTGRES_DB=loadsure_dev
    # Optionally expose postgres port for local development tools
    ports:
      - "${DEV_DB_PORT:-5433}:5432"

  # Development-specific database setup
  db-setup:
    environment:
      - NODE_ENV=development
      - DB_NAME=loadsure_dev
    command: >
      sh -c "
        echo 'Running database migrations for development...' &&
        npx sequelize-cli db:migrate &&
        echo 'Migrations completed successfully!'
      "

  # Development-specific API service settings
  api-service:
    environment:
      - NODE_ENV=development
      - DB_NAME=loadsure_dev
    command: npx nodemon src/index.js
    # More verbose logging for development
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Development-specific Loadsure service settings
  loadsure-service:
    environment:
      - NODE_ENV=development
      - DB_NAME=loadsure_dev
    command: npx nodemon src/services/loadsureService.js
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Development-specific frontend settings
  frontend:
    environment:
      - NODE_ENV=development
      - VUE_APP_API_URL=http://localhost:${API_PORT:-3001}/api
    command: npm run serve
    # Enable hot reloading for frontend development
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Development-specific queue monitor settings
  queue-monitor:
    environment:
      - NODE_ENV=development
      - DB_NAME=loadsure_dev
      
  # Development-specific nginx settings
  nginx:
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # Add development-specific logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Development-specific RabbitMQ settings  
  rabbitmq:
    # Also expose AMQP port for development tools
    ports:
      - "${DEV_RABBITMQ_PORT:-5673}:5672"
      - "${DEV_RABBITMQ_MGMT_PORT:-15673}:15672"

# Define development-specific volume names to separate from production data
volumes:
  rabbitmq_data:
    name: loadsure_rabbitmq_data_dev
  postgres_data:
    name: loadsure_postgres_data_dev
  redis_data:
    name: loadsure_redis_data_dev