services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management interface port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=loadsure
      - POSTGRES_PASSWORD=loadsurepass
      - POSTGRES_DB=loadsure_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loadsure"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - LOADSURE_API_KEY=MiphvjLVlwfZHrfhGklLgHzvjxiTbzIunOCrIAizpjVFiiRSufowtNhGGCLAiSmN
      - LOADSURE_BASE_URL=https://portal.loadsure.net
      - SUPPORT_DATA_REFRESH_SCHEDULE=0 0 * * *
      - NODE_OPTIONS=--experimental-vm-modules
      - NODE_ENV=development
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=loadsure
      - DB_PASSWORD=loadsurepass
      - DB_NAME=loadsure_dev
    volumes:
      - ./backend/data:/usr/src/app/data
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    command: node src/index.js

  loadsure-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - LOADSURE_API_KEY=MiphvjLVlwfZHrfhGklLgHzvjxiTbzIunOCrIAizpjVFiiRSufowtNhGGCLAiSmN
      - LOADSURE_BASE_URL=https://portal.loadsure.net
      - NODE_OPTIONS=--experimental-vm-modules
      - NODE_ENV=development
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=loadsure
      - DB_PASSWORD=loadsurepass
      - DB_NAME=loadsure_dev
    volumes:
      - ./backend/data:/usr/src/app/data
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    command: node src/services/loadsureService.js

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Map to nginx port inside the Vue container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api-service

volumes:
  rabbitmq_data:
  postgres_data: