services:
  postgres:
    environment:
      - POSTGRES_USER=loadsure
      - POSTGRES_PASSWORD=loadsurepass
      - POSTGRES_DB=loadsure  # This is the default database name (will be created automatically)
    command: >
      bash -c "
        echo 'Creating additional database loadsure_dev...' &&
        docker-entrypoint.sh postgres &
        sleep 10 &&
        psql -U loadsure -c 'CREATE DATABASE loadsure_dev;' || echo 'Database already exists' &&
        wait
      "

  api-service:
    environment:
      - DB_NAME=loadsure  # Match what the application is looking for
    depends_on:
      postgres:
        condition: service_healthy

  loadsure-service:
    environment:
      - DB_NAME=loadsure  # Match what the application is looking for
    depends_on:
      postgres:
        condition: service_healthy