apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: svc-loadsure
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: loadsure/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: svc-loadsure-config
              key: NODE_ENV
        - name: API_URL
          value: "http://api-service:3001"
        - name: FRONTEND_PORT
          valueFrom:
            configMapKeyRef:
              name: svc-loadsure-config
              key: FRONTEND_PORT
        - name: LOADSURE_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: svc-loadsure-config
              key: LOADSURE_BASE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: svc-loadsure
  labels:
    app: frontend
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: frontend
  type: ClusterIP