apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadsure-worker
  namespace: svc-loadsure
  labels:
    app: loadsure-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadsure-worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: loadsure-worker
    spec:
      imagePullSecrets:
      - name: do-registry
      containers:
      - name: loadsure-worker
        image: registry.digitalocean.com/svc-container-registry/loadsure-worker:latest
        imagePullPolicy: Always
        command: ["node", "src/services/loadsureService.js"]
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: svc-loadsure-config
              key: NODE_ENV
        - name: DB_DIALECT
          valueFrom:
            configMapKeyRef:
              name: svc-loadsure-config
              key: DB_DIALECT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: svc-loadsure-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: svc-loadsure-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: svc-loadsure-config
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: svc-loadsure-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: svc-loadsure-secrets
              key: DB_PASSWORD
        - name: DB_SSL
          valueFrom:
            configMapKeyRef:
              name: svc-loadsure-config
              key: DB_SSL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: svc-loadsure-config
              key: REDIS_URL
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: svc-loadsure-secrets
              key: RABBITMQ_USER
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: svc-loadsure-secrets
              key: RABBITMQ_PASSWORD
        - name: RABBITMQ_URL
          value: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq:5672"
        - name: LOADSURE_API_KEY
          valueFrom:
            secretKeyRef:
              name: svc-loadsure-secrets
              key: LOADSURE_API_KEY
        - name: WORKER_CONCURRENCY
          valueFrom:
            configMapKeyRef:
              name: svc-loadsure-config
              key: WORKER_CONCURRENCY
        - name: SUPPORT_DATA_REFRESH_SCHEDULE
          valueFrom:
            configMapKeyRef:
              name: svc-loadsure-config
              key: SUPPORT_DATA_REFRESH_SCHEDULE
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          exec:
            command: ["pgrep", "node"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3