apiVersion: v1
kind: Secret
metadata:
  name: svc-loadsure-secrets
  namespace: svc-loadsure
type: Opaque
stringData:
  DB_USERNAME: "loadsure"
  DB_PASSWORD: "your_secure_password"  # CHANGE THIS
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"  # CHANGE THIS
  LOADSURE_API_KEY: "your_api_key_here"  # CHANGE THIS