# KUBERNETES SECRETS TEMPLATE (FOR DOCUMENTATION ONLY)
# 
# This file is for documentation purposes only. The actual secrets
# are generated dynamically during deployment by the GitHub Actions workflow.
# 
# DO NOT add real credentials to this file as it is committed to the repository.
# 
# Structure of the Kubernetes secrets used in this application:

apiVersion: v1
kind: Secret
metadata:
  name: svc-loadsure-secrets
  namespace: svc-loadsure
type: Opaque
stringData:
  # Database credentials
  DB_USERNAME: "[MANAGED BY GITHUB ACTIONS]"
  DB_PASSWORD: "[MANAGED BY GITHUB ACTIONS]"
  
  # RabbitMQ credentials
  RABBITMQ_USER: "[MANAGED BY GITHUB ACTIONS]"
  RABBITMQ_PASSWORD: "[MANAGED BY GITHUB ACTIONS]"
  
  # API keys
  LOADSURE_API_KEY: "[MANAGED BY GITHUB ACTIONS]"

# NOTE: To add new secrets:
# 1. Add them to this template for documentation
# 2. Add them to the GitHub Secrets in the repository settings
# 3. Update the k8s-deploy.yml workflow to include them when generating the secrets file