apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loadsure-ingress
  namespace: svc-loadsure
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - portal.loadsure.net
    - api.loadsure.net
    secretName: loadsure-tls-cert
  rules:
  - host: portal.loadsure.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 8081
  - host: api.loadsure.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 3001